spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  h2:
    console:
      enabled: true
  task:
    execution:
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
      thread-name-prefix: DomainEvent-
    scheduling:
      pool:
        size: 5
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  redisson:
    config: |
      singleServerConfig:
        address: "redis://localhost:6379"
        connectionPoolSize: 8
        database: 0
        clientName: bank-app

server:
  port: 9091

logging:
  level:
    com.example.bank: INFO
    com.example.bank.lock: DEBUG
    org.redisson: INFO
  
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

bank:
  lock:
    timeout: 30000      # 30초 - 더 긴 대기 시간
    lease-time: 15000   # 15초 - 락 보유 최대 시간
    retry-interval: 100
    max-retry-attempts: 50 